- name: add ssh key for joshua
  authorized_key:
    user: joshua
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEW6SaEVLYMeuuJMdH+4aqValtmbKQ3MbTW1m38v1y49 ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
